### ISSUE TITLE
Community Contribution Plugins Structure

### ISSUE THREAD

**Issue by sheldonhull** [SCRT-HQ/PSProfile#34]
Consider having a plugins folder and collecting both EditorServicesPlugins, ArgumentCompleters and other plugins that could be enabled as desired. 

A library of argument completers could be really cool. 
I know PSFramework as some truly awesome argument completer functionality for automatic background caching and refreshing. Maybe you could add this as a "feature" to opt into and then folks could contribute argumentcompleters or other basic plugins. 

I updated the structure of https://github.com/poshbotio/middleware_hooks on my first contribution with this. Maybe you'd be open to it as a submodule/related repo and we could begin collecting plugins for this. 

Maybe a `Enable-PSProfileArgumentCompleter -Name PSRepositoryList -Online` and it could download from the git repo/release?

Brainstorming, as I really like this PSProfile, and just want to figure out how it could help reduce the gap to some of these really awesome things that are not easily accessible to newer powershell devs.

**Comment by scrthq** [comment]
Hey @sheldonhull - I don't why I missed responding on these issues you've opened up for so long, but I apologize! I'm open to the idea, but the plugins aspect would align more with PoshBot's own Plugin support where users could publish modules independently of PSProfile itself. That being said, I would definitely be open to getting a repo set up for community contributions and could potentially handle the deployment process to the PS Gallery if a contributor is unable to. It could be something like an `Awesome PSProfile Plugins` meta-repo.

**Comment by sheldonhull** [comment]
Closing, as cleaning up some open issues that haven't been updated in a while and this came up. rock on
