### ISSUE TITLE
Prompt Write Latency

### ISSUE THREAD

**Issue by sheldonhull** [SCRT-HQ/PSProfile#35]
I've noticed a marked difference in latency the writing of the prompt message compared to the previous Powerline block prompts I used. 

This is a placeholder, so I don't have exact debug proof, but wanted to mention, and hopefully can reproduce a simple example soon. It's noticeable enough from day 1, but not a deal breaker due to how great this is.

**Comment by scrthq** [comment]
@sheldonhull - Is this still an issue for you? I'd love to know more!

**Comment by sheldonhull** [comment]
Thanks! I've been swamped so don't know if I can do much on this right now. As much as I love PSProfile, and want to revisit, I ended up using starship just for the basic prompt right now and hope to have time to work on more customization later.

**Comment by scrthq** [comment]
got it @sheldonhull ! Haven't heard of Starship before but it looks pretty rad!

**Comment by sheldonhull** [comment]
regardless, I always love the stuff you build :-) Look forward to collaborating again hopefully soon
